"""created portfolio stocks

Revision ID: aa0a3b5c1185
Revises: 7be3c375cd9f
Create Date: 2021-07-17 23:16:09.001285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0a3b5c1185'
down_revision = '7be3c375cd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('portfolio_stocks_user_id_fkey', 'portfolio_stocks', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_stocks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('watchlist_stocks_user_id_fkey', 'watchlist_stocks', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist_stocks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist_stocks', type_='foreignkey')
    op.create_foreign_key('watchlist_stocks_user_id_fkey', 'watchlist_stocks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'portfolio_stocks', type_='foreignkey')
    op.create_foreign_key('portfolio_stocks_user_id_fkey', 'portfolio_stocks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
